version: "3.8"
services:
  zoobiblioarch:
    build: .
    volumes:
      - .:/zoobiblioarch
    ports:
      - 8000:8000
    image: zoobibioarch:zoobibioarch
    container_name: zoobiblioarch_container
    command: python manage.py runserver 0.0.0.0:8000
    