# Generated by Django 3.1.7 on 2022-05-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slider_description', models.CharField(max_length=100)),
                ('slider_image', models.FileField(blank=True, null=True, upload_to='slider_images/')),
                ('order', models.IntegerField()),
                ('slug', models.CharField(max_length=100)),
                ('slider_online', models.BooleanField(default=True)),
            ],
        ),
    ]
