# Generated by Django 3.2.12 on 2022-06-10 05:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='<h3>The name of the Museum(e.g., The Met Museum )</h3>', max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bundle_images/')),
                ('description', ckeditor.fields.RichTextField(blank=True, default=None, max_length=10000, null=True)),
                ('sameAs', models.URLField(blank=True)),
                ('slug', models.SlugField(max_length=100)),
                ('order', models.IntegerField()),
                ('online', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bundle',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default=None, help_text='<h3>Last name of the Maker:(e.g., Da Vinci )</h3>', max_length=50, unique=True)),
                ('first_name', models.CharField(blank=True, default=None, max_length=50, verbose_name='First Name')),
                ('gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('type', models.CharField(blank=True, choices=[('actor', 'Actor'), ('artist', 'Artist'), ('author', 'Author'), ('composer', 'Composer'), ('creator', 'Creator'), ('painter', 'Painter'), ('draughtsman', 'Draughtsman'), ('engineer', 'Engineer'), ('scientist', 'Scientist'), ('sculptor ', 'Sculptor'), ('architect ', 'Architect'), ('polymath ', 'Polymath'), ('colorist ', 'colorist')], default=None, max_length=30, null=True)),
                ('photo', models.ImageField(upload_to='maker_images')),
                ('date_of_birth', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('birth_place', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('date_of_death', models.CharField(blank=True, max_length=30)),
                ('death_place', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('online', models.BooleanField(default=True, verbose_name='Online')),
                ('same_as', models.URLField(blank=True, default=None, help_text='<h3>it is the same person as the link (https://en.wikipedia.org/wiki/Leonardo_da_Vinci)</h3>', max_length=100, null=True)),
                ('order', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Maker',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='<h3>The name of the Museum(e.g., The Met Museum )</h3>', max_length=50, unique=True)),
                ('classification', models.CharField(blank=True, choices=[('CivicStructure', 'Civic Structure'), ('Museum', 'Museum'), ('PlaceOfWorship', 'PlaceOfWorship'), ('Airport', 'Airport'), ('PlaceOfWorship', 'PlaceOfWorship')], max_length=60, null=True)),
                ('working_hours', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('logo', models.ImageField(upload_to='logo_images')),
                ('phone', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, default=None, max_length=10000, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('sameAs', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100)),
                ('order', models.IntegerField()),
                ('online', models.BooleanField(default=True, verbose_name='Online')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Place',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slider_description', models.CharField(max_length=100)),
                ('slider_image', models.FileField(blank=True, null=True, upload_to='slider_images/')),
                ('order', models.IntegerField()),
                ('slug', models.CharField(max_length=100)),
                ('online', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreativeWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(blank=True, max_length=60, null=True)),
                ('title', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('classification', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Drawing', 'Drawing'), ('Book', 'Book'), ('Map', 'Map'), ('Painting', 'Painting'), ('Photograph', 'Photograph'), ('Manuscripts', 'Manuscripts'), ('Posters', 'Posters'), ('Sculptures', 'Sculptures'), ('VisualArtwork', 'VisualArtwork'), ('Vases', 'Vases'), ('Bronzes', ' Bronze'), ('Terracottas', 'Terracottas'), ('Currency', 'Currency'), ('Paintings-Icons', 'Paintings-Icons'), ('Sculptures', 'Sculpture')], max_length=60, null=True)),
                ('date', models.CharField(blank=True, max_length=30, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True)),
                ('image_one', models.ImageField(upload_to='creativeworks/image_one_items')),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('creditline', models.CharField(blank=True, max_length=60, null=True)),
                ('accession_number', models.CharField(blank=True, max_length=60, null=True)),
                ('sameAs', models.URLField(blank=True, null=True)),
                ('culture', models.CharField(blank=True, max_length=30, null=True)),
                ('medium', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Oil on canvas', 'Oil on Canvas'), ('Limestone', 'Limestone')], max_length=60, null=True)),
                ('period', models.CharField(blank=True, max_length=30, null=True)),
                ('rights_reproduction', models.CharField(blank=True, max_length=130, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField()),
                ('online', models.BooleanField(default=True, verbose_name='Online')),
                ('bundle', models.ManyToManyField(to='cyprusark.Bundle')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cyprusark.person')),
            ],
            options={
                'verbose_name': 'Creative Work',
            },
        ),
    ]
