# Generated by Django 3.1.7 on 2022-06-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creativework',
            name='test',
        ),
        migrations.AddField(
            model_name='creativework',
            name='title_one',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
