# Generated by Django 3.1.7 on 2022-05-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(default=None, help_text='<h3>The name of the Museum(e.g., The Met Museum )</h3>', max_length=30, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='collection_images/')),
                ('description', models.TextField(default=None, max_length=300)),
                ('online', models.BooleanField(default=True)),
                ('sameAs', models.URLField(blank=True)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Collection',
            },
        ),
    ]
