# Generated by Django 3.1.7 on 2022-06-10 06:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0002_auto_20220610_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creativework',
            name='title_one',
        ),
        migrations.CreateModel(
            name='CreativeWork_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('classification', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Drawing', 'Drawing'), ('Book', 'Book'), ('Map', 'Map'), ('Painting', 'Painting'), ('Photograph', 'Photograph'), ('Manuscripts', 'Manuscripts'), ('Posters', 'Posters'), ('Sculptures', 'Sculptures'), ('VisualArtwork', 'VisualArtwork'), ('Vases', 'Vases'), ('Bronzes', ' Bronze'), ('Terracottas', 'Terracottas'), ('Currency', 'Currency'), ('Paintings-Icons', 'Paintings-Icons'), ('Sculptures', 'Sculpture')], max_length=60, null=True)),
                ('date', models.CharField(blank=True, max_length=30, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True)),
                ('image_one', models.ImageField(upload_to='creativeworks/image_one_items')),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('creditline', models.CharField(blank=True, max_length=60, null=True)),
                ('accession_number', models.CharField(blank=True, max_length=60, null=True)),
                ('sameAs', models.URLField(blank=True, null=True)),
                ('culture', models.CharField(blank=True, max_length=30, null=True)),
                ('medium', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Oil on canvas', 'Oil on Canvas'), ('Limestone', 'Limestone')], max_length=60, null=True)),
                ('period', models.CharField(blank=True, max_length=30, null=True)),
                ('rights_reproduction', models.CharField(blank=True, max_length=130, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField()),
                ('online', models.BooleanField(default=True, verbose_name='Online')),
                ('bundle', models.ManyToManyField(to='cyprusark.Bundle')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cyprusark.person')),
            ],
            options={
                'verbose_name': 'Creative Work',
            },
        ),
    ]
