# Generated by Django 3.1.7 on 2022-05-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0002_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='slider_online',
            new_name='online',
        ),
        migrations.AddField(
            model_name='collection',
            name='order',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
