# Generated by Django 3.1.7 on 2022-06-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0003_auto_20220610_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativework_one',
            name='test',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
