# Generated by Django 3.1.7 on 2022-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0003_auto_20220511_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('museum_name', models.CharField(default=None, help_text='<h3>The name of the Museum(e.g., The Met Museum )</h3>', max_length=50, unique=True)),
                ('working_hours', models.CharField(default=None, max_length=30)),
                ('address', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=30)),
                ('country', models.CharField(default=None, max_length=80)),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='museum_a/museum_logo_images/%Y/%m/%d/')),
                ('phone', models.CharField(default=None, max_length=80)),
                ('description', models.TextField(default=None, max_length=1000)),
                ('museum_website', models.URLField()),
                ('sameAs', models.URLField(blank=True)),
                ('online', models.BooleanField(default=True, verbose_name='Online')),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Museum',
            },
        ),
    ]
