# Generated by Django 3.1.7 on 2022-06-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0004_creativework_one_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativework',
            name='test',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='CreativeWork_one',
        ),
    ]
