# Generated by Django 3.1.7 on 2022-05-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0005_auto_20220511_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum',
            name='logo',
            field=models.ImageField(upload_to='museum/museum_logo_images'),
        ),
        migrations.CreateModel(
            name='Museum_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('classification', models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Drawing', 'Drawing'), ('Book', 'Book'), ('Map', 'Map'), ('Painting', 'Painting'), ('Photograph', 'Photograph'), ('Manuscripts', 'Manuscripts'), ('Posters', 'Posters'), ('Sculptures', 'Sculptures'), ('VisualArtwork', 'VisualArtwork'), ('Vases', 'Vases'), ('Bronzes', ' Bronze'), ('Terracottas', 'Terracottas'), ('Coins', 'Coins'), ('Paintings-Icons', 'Paintings-Icons')], max_length=60, null=True)),
                ('date', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='museum_items/image_one_items')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='museum_items/image_two_items')),
                ('dimensions', models.CharField(blank=True, max_length=50, null=True)),
                ('creditline', models.CharField(blank=True, max_length=60, null=True)),
                ('accession_number', models.CharField(blank=True, max_length=60, null=True)),
                ('sameAs', models.URLField(blank=True, null=True)),
                ('culture', models.CharField(blank=True, max_length=30, null=True)),
                ('medium', models.CharField(blank=True, max_length=30, null=True)),
                ('period', models.CharField(blank=True, max_length=30, null=True)),
                ('rights_reproduction', models.CharField(blank=True, max_length=130, null=True)),
                ('online', models.BooleanField(default=True, verbose_name='Online')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField()),
                ('collection', models.ManyToManyField(default=1, null=True, to='cyprusark.Collection')),
            ],
            options={
                'verbose_name': 'Museum item',
            },
        ),
    ]
