# Generated by Django 3.2.12 on 2022-06-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0005_auto_20220610_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creativework',
            name='test',
        ),
    ]
