# Generated by Django 3.2.12 on 2022-06-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0006_remove_creativework_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='medium',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Oil on canvas', 'Oil on canvas'), ('Oil on wood', 'Oil on wood'), ('Limestone', 'Limestone')], max_length=60, null=True),
        ),
    ]
