# Generated by Django 3.1.7 on 2022-05-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0006_auto_20220512_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museum_item',
            name='collection',
            field=models.ManyToManyField(null=True, to='cyprusark.Collection'),
        ),
    ]
