# Generated by Django 3.1.7 on 2022-05-12 13:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0007_auto_20220512_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='museum',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='museum_item',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True),
        ),
    ]
