# Generated by Django 3.1.7 on 2022-06-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0007_alter_creativework_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='classification',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Drawing', 'Drawing'), ('Book', 'Book'), ('Map', 'Map'), ('Painting', 'Painting'), ('Photograph', 'Photograph'), ('Manuscript', 'Manuscript'), ('Poster', 'Poster'), ('Sculpture', 'Sculpture'), ('VisualArtwork', 'VisualArtwork'), ('Vases', 'Vases'), ('Bronzes', ' Bronze'), ('Terracottas', 'Terracottas'), ('Currency', 'Currency'), ('Paintings-Icons', 'Paintings-Icons')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='classification',
            field=models.CharField(blank=True, choices=[('CivicStructure', 'Civic Structure'), ('Museum', 'Museum'), ('Church', 'Church'), ('PlaceOfWorship', 'PlaceOfWorship'), ('Airport', 'Airport'), ('PlaceOfWorship', 'PlaceOfWorship')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.FileField(blank=True, default='/slider_images/slider01.jpg', null=True, upload_to='slider_images/'),
        ),
    ]
