# Generated by Django 3.2.12 on 2022-06-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0012_person_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creativework',
            name='classification',
        ),
        migrations.AddField(
            model_name='creativework',
            name='typeof',
            field=models.CharField(choices=[('Think > Creative Work', (('CreativeWork', 'CreativeWork'), ('Book', 'Book'), ('Sculpture', ' Sculpture'), ('Painting', ' Painting'), ('VisualArtwork', 'VisualArtwork'), ('Photograph', '  Photograph'), ('Manuscript', 'Manuscript'), ('MediaObject', 'MediaObject'), ('Drawing', 'Drawing'), ('Map', 'Map'))), ('Thing > Place', (('CivicStructure', 'CivicStructure'), ('LandmarksOrHistoricalBuildings', 'LandmarksOrHistoricalBuildings')))], default=-1, max_length=80),
            preserve_default=False,
        ),
    ]
