# Generated by Django 3.2.12 on 2022-07-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0013_auto_20220622_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='classification',
            field=models.CharField(blank=True, choices=[('Place', 'Place'), ('Residence', 'Residence'), ('CivicStructure', 'Civic Structure'), ('LandmarksOrHistoricalBuildings', 'LandmarksOrHistoricalBuildings'), ('Museum', 'Museum'), ('Church', 'Church'), ('Mosque', 'Mosque'), ('Synagogue', 'Synagogue'), ('Cemetery', 'Cemetery'), ('PlaceOfWorship', 'PlaceOfWorship')], max_length=60, null=True),
        ),
    ]
