# Generated by Django 3.2.12 on 2022-07-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0018_auto_20220705_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativework',
            name='Type',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('ArchiveComponent', 'ArchiveComponent'), ('CreativeWork', 'CreativeWork'), ('Book', 'Book'), ('DigitalDocument', 'DigitalDocument'), ('Drawing', 'Drawing'), ('Manuscript', 'Manuscript'), ('Map', 'Map'), ('MediaObject', 'MediaObject'), ('ImageObject', 'ImageObject'), ('3DModel', '3DModel'), ('Painting', 'Painting'), ('Photograph', 'Photograph'), ('Sculpture', 'Sculpture'), ('VisualArtwork', 'VisualArtwork')], max_length=60, null=True),
        ),
    ]
