# Generated by Django 3.2.12 on 2022-07-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0019_creativework_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creativework',
            old_name='Type',
            new_name='type',
        ),
    ]
