# Generated by Django 3.2.12 on 2022-07-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0020_rename_type_creativework_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creativework',
            old_name='type',
            new_name='artform',
        ),
        migrations.RemoveField(
            model_name='creativework',
            name='medium',
        ),
        migrations.AddField(
            model_name='creativework',
            name='art_medium',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Oil', 'Oil'), ('Watercolour', 'Watercolour'), ('Acrylic', 'Acrylic'), ('Marble', 'Marble'), ('Digital, Lithograph', 'Digital, Lithograph'), ('Pastel', 'Pastel'), ('Woodcut', 'Woodcut'), ('Pencil', 'Pencil'), ('Mixed Media', 'Mixed Media')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='creativework',
            name='artworkSurface',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Canvas', 'Canvas'), ('Paper', 'Paper'), ('Wood', 'Wood'), ('Board', 'Board')], max_length=60, null=True),
        ),
    ]
