# Generated by Django 3.2.12 on 2022-07-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0021_auto_20220705_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='artworkSurface',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Canvas', 'Canvas'), ('Paper', 'Paper'), ('Wood', 'Wood'), ('Board', 'Board'), ('Bronze', 'Bronze')], max_length=60, null=True),
        ),
    ]
