# Generated by Django 3.1.7 on 2022-07-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0022_alter_creativework_artworksurface'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativework',
            name='additionalType',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Icon', 'Icon'), ('Coin', 'Coin')], max_length=60, null=True),
        ),
    ]
