# Generated by Django 3.1.7 on 2022-07-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyprusark', '0024_auto_20220708_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativework',
            name='additionalType',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Icon', 'Icon'), ('https://dbpedia.org/page/Coin', 'https://dbpedia.org/page/Coin')], max_length=60, null=True),
        ),
    ]
