# Generated by Django 3.0 on 2022-11-21 09:08

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('zoobiblioarch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='zoobiblioarch.Author'),
        ),
    ]
