# Generated by Django 3.0 on 2022-12-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoobiblioarch', '0003_auto_20221123_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rigion_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
