# Generated by Django 3.0 on 2022-12-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoobiblioarch', '0004_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='region',
            field=models.ManyToManyField(blank=True, to='zoobiblioarch.Region'),
        ),
    ]
