# Generated by Django 3.0 on 2022-12-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoobiblioarch', '0005_article_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='rigion_name',
            new_name='region_name',
        ),
    ]
